version: '3.8'

services:
  ecoshop-frontend:
    build:
      context: ./FrontEnd/ecoshop
      dockerfile: Dockerfile
    container_name: ecoshop-frontend
    ports:
      - "4200:80"
    depends_on:
      - ecoshop-backend

  ecoshop-backend:
    depends_on:
      - mysqldb
    build:
      context: ./BackEnd/ecoshop
      dockerfile: Dockerfile
    container_name: ecoshop-backend
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
  mysqlvolume: